// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Cau4LTTQ.Models;

public partial class Cau4LTTQContext : DbContext
{
    public Cau4LTTQContext()
    {
    }

    public Cau4LTTQContext(DbContextOptions<Cau4LTTQContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BacSi> BacSis { get; set; }

    public virtual DbSet<LichKham> LichKhams { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=localhost\\SQLEXPRESS;Initial Catalog=Cau4LTTQ;Integrated Security=True;Trust Server Certificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BacSi>(entity =>
        {
            entity.HasKey(e => e.MaBs).HasName("PK__BacSi__272475968EECF6A5");

            entity.ToTable("BacSi");

            entity.Property(e => e.MaBs).HasColumnName("MaBS");
            entity.Property(e => e.ChuyenKhoa).HasMaxLength(100);
            entity.Property(e => e.HoTen)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Sdt)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("SDT");
        });

        modelBuilder.Entity<LichKham>(entity =>
        {
            entity.HasKey(e => e.MaLich).HasName("PK__LichKham__728A9AE9C13704B2");

            entity.ToTable("LichKham");

            entity.Property(e => e.GioKham).HasPrecision(0);
            entity.Property(e => e.MaBs).HasColumnName("MaBS");
            entity.Property(e => e.Sdt)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("SDT");
            entity.Property(e => e.TenBenhNhan)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TrangThai)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Chờ khám")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_LichKham_TrangThai");

            entity.HasOne(d => d.MaBsNavigation).WithMany(p => p.LichKhams)
                .HasForeignKey(d => d.MaBs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LichKham_BacSi");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}